name: Cypress

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
      - b0.*

jobs:
  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v4
        with:
          start: yarn test:cypress
          wait-on-timeout: 120
          browser: chrome
          group: 'UI - Chrome'
          spec: tests/cypress/ui/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: ./cypress/videos

