name: Cypress

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
      - b0.*

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.0'
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: npm install
          build: npm run build

