name: Cypress

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
      - b0.*

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.0'
      - name: Cypress run
        run: |
          npm install
          npm run build
          npm run test:cypress
