name: Lint

on:
  push:
    branches:
      - master
      - b0.*
  pull_request:
    branches:
      - master
      - b0.*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Run ESLint
      uses: actions/checkout@v2
      run: |
        yarn install
        yarn lint
