name: Lint, Build, Test

on:
  pull_request:
    branches:
      - master
      - next
      - beta
      - alpha

  # Allows triggering the workflow manually
  workflow_dispatch:

jobs:
  regular-checks:
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x, 20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Perform regular checks
        run: |
          npm install
          npm run format:check
          npm run lint
          npm run test:unit
          npm run build
